server {
    listen 80;
    server_name _; # Accepte les connexions sur l'IP ou ton domaine

    root /usr/local/www/life-switch/dist;
    index index.html;

    # Support du Single Page Application (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optimisation du cache
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    # Sécurité
    server_tokens off;
    
    # Compression pour la vitesse
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml+rss text/javascript;
}
